import Pages from "./Routes";
import Home from "./Home";
import News from "./News";
import Navigation from "./NavBar";
import WhoAreWe from "./WhoAreWe";

export const metadata = {
  title: "Dark League Studios",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <head>
      <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
      </head>
      <body>
        <Navigation/>
      </body>
    </html>
  );
}
